@startuml Login (POST)

header Campground Booking Sqeunce Diagram
title "Login (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:Users" as modelUser
database "<<MongoDB>>\n:Users" as UsersDatabase

client->server ++:req.post('/auth/login')
server->routerAuth ++:app.use('/auth', auth)
routerAuth ->controllersAuth ++:login()
controllersAuth ->modelUser ++:findOne(req.email), match(req.password)
modelUser -> UsersDatabase ++:UsersSchema
UsersDatabase --> modelUser --:user
modelUser --> controllersAuth --:user
controllersAuth -> client --:response

@enduml
