@startuml Manage Booking (PUT)

header Campground Booking Sqeunce Diagram
title "Manage Booking (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Bookings" as BookingModel
database "<<MongoDB>>\n:Bookings" as BookingsDatabase

client->server ++:req.post('/bookings/:bookingId')
server->routerBookings ++:app.use('/bookings', bookings)
routerBookings -> middlewareAuth ++:protect()
middlewareAuth --> routerBookings --:client data
routerBookings -> controllersBookings ++:updateBooking()
controllersBookings -> BookingModel ++:findByIdAndUpdate(req.params.id, req.body)
BookingModel -> BookingsDatabase ++:BookingSchema
BookingsDatabase --> BookingModel --:booking
BookingModel --> controllersBookings --:booking
controllersBookings -> client --:response

@enduml